# Copyright Neomadas, Inc. All rights reserved.
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--preview, -l80]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black, --line-length=80]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length=80]

default_language_version:
  python: python3

default_stages: [commit]
default_install_hook_types: [pre-commit, pre-push]
